language: python
python:
  - "3.5"
  - "3.6"
install:
    - pip install -e .
    - pip install codecov pytest-cov
    - pip install hypothesis
script:
    - pytest --cov=freqgen
cache: pip
after_success:
    - codecov
